Gemfile
Gemfile.lock
app/models/user.rb
app/views/users/registrations/new.html.erb
config/routes.rb
spec/models/user_spec.rb

1026 1user tan test

---

Gemfile
Gemfile.lock
app/models/tweet.rb
app/models/user.rb
app/views/tweets/index.html.erb
config/application.rb
spec/factories/tweets.rb
spec/factories/users.rb
spec/models/tweet_spec.rb
spec/models/user_spec.rb
spec/requests/hello_spec.rb

Tweetモデルの単体テストを作成しました。
今回は、factory_bot_railsを使用してます。

Tweetモデルの単体テストを作成しよう

---

app/models/user.rb
app/views/tweets/index.html.erb
spec/helpers/users_helper_spec.rb
spec/models/user_spec.rb
spec/requests/users_spec.rb

User単体テストの修正を行いました。
しかし、１つエラーが直りません。

User単体テストの修正を行いました。

---

app/controllers/tweets_controller.rb
app/views/tweets/index.html.erb
db/migrate/20211031102924_add_completed_to_tweets.rb
db/schema.rb

timeカラムがストロングパラメーターに記載がないことがわかりました。
そこで修正を行うとともに、completedカラムを追加しました。

DBにtimeカラムとcompletedカラムを登録できるようにしよう

---

Gemfile
Gemfile.lock
app/controllers/tweets_controller.rb
spec/requests/hello_spec.rb
spec/requests/tweets_spec.rb

Helloコントローラーの作成

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/tweets_controller.rb
app/models/tweet.rb
app/views/tweets/_tweets.html.erb
app/views/tweets/show.html.erb
config/application.rb
config/locales/ja.yml
config/routes.rb

tweetモデルのcompletedカラムにenumでステータス更新に機能をつけたいがエラーが出てしまう

eumuによるステータス更新をかけるときにエラーが出てしまう

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/javascript/packs/application.js
app/views/tweets/_tweets.html.erb
package.json
yarn.lock

ファントオーサムを導入してわかやすいようにデザインを整えました。

フォントオーサムを導入しました

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/javascript/packs/application.js
app/views/tweets/_tweets.html.erb
app/views/tweets/index.html.erb
package.json
yarn.lock

Search index

---

app/views/tweets/_tweets.html.erb

インデックスのデザインを整えました。
今までは、担当者しかわからなかったのを修正しました。またshow画面にコメント機能を非同期で作成しようと思っています。

Index design

---

app/controllers/tweets_controller.rb
app/views/tweets/_tweets.html.erb
app/views/tweets/index.html.erb

検索機能も実装できるように直しました

---

app/controllers/tweets_controller.rb
app/views/tweets/_tweets.html.erb
app/views/tweets/edit.html.erb
config/routes.rb

エディット画面が存在しなかったので、作成しました。まだ中身は作成していない。

エディット画面を追加しました。

---

app/controllers/tweets_controller.rb
app/views/tweets/_tweets.html.erb
app/views/tweets/edit.html.erb
config/routes.rb

Reverts takumifujiwaradairy/WorkShare#27

Revert "エディット画面を追加しました。"

---

Gemfile
Gemfile.lock
app/controllers/tweets_controller.rb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/tweets/index.html.erb
config/initializers/kaminari_config.rb

kaminariを導入したのだが、ransackと打ち消し合っているのか、うまく表示ができない！

ページネーションを追加使用としたのでしが、うまく行かない

---

app/assets/stylesheets/users.scss
app/views/users/show.html.erb

マイページのデザインを整えました

---

app/views/users/registrations/edit.html.erb

userのエディットページをデザインを修正しました

---

app/assets/stylesheets/likes.scss
app/controllers/likes_controller.rb
app/helpers/likes_helper.rb
app/models/like.rb
app/models/tweet.rb
app/models/user.rb
app/views/tweets/_tweets.html.erb
config/routes.rb
db/migrate/20211122133454_create_likes.rb
db/schema.rb
spec/factories/likes.rb
spec/models/like_spec.rb
spec/requests/likes_spec.rb

like機能を追加しました

---

app/assets/stylesheets/comments.scss
app/controllers/comments_controller.rb
app/controllers/tweets_controller.rb
app/helpers/comments_helper.rb
app/models/comment.rb
app/models/tweet.rb
app/models/user.rb
app/views/tweets/show.html.erb
config/routes.rb
db/migrate/20211123064602_create_comments.rb
db/schema.rb
spec/factories/comments.rb
spec/models/comment_spec.rb
spec/requests/comments_spec.rb

コメント機能を追加しました。

---

app/views/tweets/show.html.erb

コメント機能を修正しました。

---

app/controllers/comments_controller.rb
app/controllers/tweets_controller.rb
app/views/tweets/create.js.erb

投稿機能の修正を行いました

---

Gemfile
Gemfile.lock
config/database.yml
config/environments/production.rb

herokuへアップロードするための下準備

---

app/controllers/tweets_controller.rb
app/views/tweets/_tweets.html.erb
app/views/tweets/edit.html.erb
config/routes.rb

Reverts takumifujiwaradairy/WorkShare#37

Revert "Revert "エディット画面を追加しました。""

---

app/assets/stylesheets/tweets.scss
app/controllers/comments_controller.rb
app/views/tweets/show.html.erb
config/application.rb
config/initializers/time_formats.rb
db/schema.rb
spec/factories/comments.rb
spec/requests/comments_spec.rb

コメント機能に時間を表示できるようにしました

---

app/assets/stylesheets/tweets.scss
app/controllers/comments_controller.rb
app/controllers/tweets_controller.rb
app/views/tweets/_tweets.html.erb
app/views/tweets/show.html.erb
config/application.rb
config/initializers/time_formats.rb
db/migrate/20211128035750_change_completed_of_tweets.rb
db/schema.rb
spec/factories/comments.rb
spec/requests/comments_spec.rb

インデックス画面にステータスを表示できるように変更しました。

Add index state

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/hello.scss
app/assets/stylesheets/tweets.scss
app/controllers/tweets_controller.rb
app/views/tweets/_tweets.html.erb
app/views/tweets/index.html.erb
app/views/tweets/show.html.erb
config/initializers/time_formats.rb
db/migrate/20211128035750_change_completed_of_tweets.rb
db/schema.rb

インデックス画面のデザイン

---

app/views/tweets/show.html.erb

クリエイトアクションを修正しました

---

Gemfile

herokuのSpringに修正
